In [36]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pickle as pkl

%matplotlib inline

In [43]:
df = pd.read_csv(r"..\data\heart_cleaned.csv")

In [44]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [45]:
df.drop_duplicates(inplace=True)

df.shape

(302, 14)

In [46]:
df.columns

Index(['age', 'sex', 'chest_pain_type', 'resting_blood_pressure',
       'cholestoral', 'fasting_blood_sugar', 'rest_ecg', 'Max_heart_rate',
       'exercise_induced_angina', 'oldpeak', 'slope',
       'vessels_colored_by_flourosopy', 'thalassemia', 'target'],
      dtype='str')

### Ordinal Encoding

In [47]:
categories_order = [['Zero', 'One', 'Two', 'Three', 'Four']]
orde = OrdinalEncoder(categories=categories_order)

In [48]:
df['vessels_colored_by_flourosopy_encoded'] = orde.fit_transform(df[['vessels_colored_by_flourosopy']])

In [49]:
df['vessels_colored_by_flourosopy_encoded'].value_counts()

vessels_colored_by_flourosopy_encoded
0.0    175
1.0     65
2.0     38
3.0     20
4.0      4
Name: count, dtype: int64

In [50]:
categories_order_slope = [['Upsloping', 'Flat', 'Downsloping']]
ordencode = OrdinalEncoder(categories=categories_order_slope)

df[['slope_encode']] = ordencode.fit_transform(df[['slope']])

In [51]:
print(df['slope_encode'].value_counts())
print(df['slope'].value_counts())

slope_encode
2.0    141
1.0    140
0.0     21
Name: count, dtype: int64
slope
Downsloping    141
Flat           140
Upsloping       21
Name: count, dtype: int64

### Label Encoding

In [52]:
label_enc = LabelEncoder()

In [53]:
df['sex_enc'] = label_enc.fit_transform(df['sex'])

In [54]:
print(df['sex'].value_counts())
print(df['sex_enc'].value_counts())

sex
Male      206
Female     96
Name: count, dtype: int64
sex_enc
1    206
0     96
Name: count, dtype: int64

In [55]:
df['fasting_blood_sugar_encode'] = label_enc.fit_transform(df['fasting_blood_sugar'])

In [56]:
print(df['fasting_blood_sugar'].value_counts())
print(df['fasting_blood_sugar_encode'].value_counts())

fasting_blood_sugar
Lower than 120 mg/ml      257
Greater than 120 mg/ml     45
Name: count, dtype: int64
fasting_blood_sugar_encode
1    257
0     45
Name: count, dtype: int64

In [57]:
df['exercise_induced_angina_encode'] = label_enc.fit_transform(df['exercise_induced_angina'])

In [58]:
print(df['exercise_induced_angina'].value_counts())
print(df['exercise_induced_angina_encode'].value_counts())

exercise_induced_angina
No     203
Yes     99
Name: count, dtype: int64
exercise_induced_angina_encode
0    203
1     99
Name: count, dtype: int64

In [75]:
df_encoded = df.copy()
df_encoded

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target,vessels_colored_by_flourosopy_encoded,slope_encode,sex_enc,fasting_blood_sugar_encode,exercise_induced_angina_encode
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0,2.0,2.0,1,1,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0,0.0,0.0,1,0,1
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0,0.0,0.0,1,1,1
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0,1.0,2.0,1,1,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0,3.0,1.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,68,Female,Non-anginal pain,120,211,Lower than 120 mg/ml,Normal,115,No,1.5,Flat,Zero,Fixed Defect,1,0.0,1.0,0,1,0
298,44,Female,Non-anginal pain,108,141,Lower than 120 mg/ml,ST-T wave abnormality,175,No,0.6,Flat,Zero,Fixed Defect,1,0.0,1.0,0,1,0
299,52,Male,Typical angina,128,255,Lower than 120 mg/ml,ST-T wave abnormality,161,Yes,0.0,Downsloping,One,Reversable Defect,0,1.0,2.0,1,1,1
300,59,Male,Asymptomatic,160,273,Lower than 120 mg/ml,Normal,125,No,0.0,Downsloping,Zero,Fixed Defect,0,0.0,2.0,1,1,0
301,54,Male,Typical angina,120,188,Lower than 120 mg/ml,ST-T wave abnormality,113,No,1.4,Flat,One,Reversable Defect,0,1.0,1.0,1,1,0

In [76]:
df_encoded = df_encoded.drop(columns=['vessels_colored_by_flourosopy', 'slope', 'sex', 'fasting_blood_sugar','exercise_induced_angina'])
df_encoded.head()

,age,chest_pain_type,resting_blood_pressure,cholestoral,rest_ecg,Max_heart_rate,oldpeak,thalassemia,target,vessels_colored_by_flourosopy_encoded,slope_encode,sex_enc,fasting_blood_sugar_encode,exercise_induced_angina_encode
0,52,Typical angina,125,212,ST-T wave abnormality,168,1.0,Reversable Defect,0,2.0,2.0,1,1,0
1,53,Typical angina,140,203,Normal,155,3.1,Reversable Defect,0,0.0,0.0,1,0,1
2,70,Typical angina,145,174,ST-T wave abnormality,125,2.6,Reversable Defect,0,0.0,0.0,1,1,1
3,61,Typical angina,148,203,ST-T wave abnormality,161,0.0,Reversable Defect,0,1.0,2.0,1,1,0
4,62,Typical angina,138,294,ST-T wave abnormality,106,1.9,Fixed Defect,0,3.0,1.0,0,0,0

In [77]:
df_encoded.rename(columns={'vessels_colored_by_flourosopy_encoded':'vessels_colored_by_flourosopy',
       'slope_encode':'slope', 'sex_enc':'sex', 'fasting_blood_sugar_encode':'fasting_blood_sugar',
       'exercise_induced_angina_encode':'exercise_induced_angina'}, inplace=True)

In [79]:
df_encoded.to_csv('../data/heart_feature_encoded.csv', index=False)

### One-Hot Encoding

In [18]:
one_hot = OneHotEncoder(sparse_output=False)

In [19]:
cat_one_hot = ['chest_pain_type', 'rest_ecg', 'thalassemia']

one_hot_encoded = one_hot.fit_transform(df[cat_one_hot])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=one_hot.get_feature_names_out(cat_one_hot))
one_hot_df.head()

,chest_pain_type_Asymptomatic,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,rest_ecg_Left ventricular hypertrophy,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [20]:
df_encode = pd.concat([df, one_hot_df], axis=1)

In [21]:
df_encode.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,...,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,rest_ecg_Left ventricular hypertrophy,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [ ]:
cat_col = ['sex', 'chest_pain_type', 'fasting_blood_sugar',	'rest_ecg',	'exercise_induced_angina',	'slope', 'vessels_colored_by_flourosopy', 'thalassemia']

In [62]:
df_encode = df_encode.drop(cat_col, axis=1)
df_encode.head()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target,chest_pain_type_Asymptomatic,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,rest_ecg_Left ventricular hypertrophy,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,-0.267966,-0.376556,-0.667728,0.806035,-0.037124,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,-0.157260,0.478910,-0.841918,0.237495,1.773958,0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1.724733,0.764066,-1.403197,-1.074521,1.342748,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.728383,0.935159,-0.841918,0.499898,-0.899544,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.839089,0.364848,0.919336,-1.905464,0.739054,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [63]:
df_encode.columns

Index(['age', 'resting_blood_pressure', 'cholestoral', 'Max_heart_rate',
       'oldpeak', 'target', 'chest_pain_type_Asymptomatic',
       'chest_pain_type_Atypical angina', 'chest_pain_type_Non-anginal pain',
       'chest_pain_type_Typical angina',
       'rest_ecg_Left ventricular hypertrophy', 'rest_ecg_Normal',
       'rest_ecg_ST-T wave abnormality', 'thalassemia_Fixed Defect',
       'thalassemia_No', 'thalassemia_Normal',
       'thalassemia_Reversable Defect'],
      dtype='str')

In [26]:
df_encode.columns

Index(['age', 'resting_blood_pressure', 'cholestoral', 'Max_heart_rate',
       'oldpeak', 'target', 'vessels_colored_by_flourosopy', 'slope', 'sex',
       'fasting_blood_sugar', 'exercise_induced_angina',
       'chest_pain_type_Asymptomatic', 'chest_pain_type_Atypical angina',
       'chest_pain_type_Non-anginal pain', 'chest_pain_type_Typical angina',
       'rest_ecg_Left ventricular hypertrophy', 'rest_ecg_Normal',
       'rest_ecg_ST-T wave abnormality', 'thalassemia_Fixed Defect',
       'thalassemia_No', 'thalassemia_Normal',
       'thalassemia_Reversable Defect'],
      dtype='str')

In [37]:
num_col = ['age', 'resting_blood_pressure', 'cholestoral', 'Max_heart_rate', 'oldpeak', 'vessels_colored_by_flourosopy']

In [38]:
df_num = df[['age', 'resting_blood_pressure', 'cholestoral', 'Max_heart_rate', 'oldpeak', 'vessels_colored_by_flourosopy']]
df_num.head()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,vessels_colored_by_flourosopy
0,52,125,212,168,1.0,Two
1,53,140,203,155,3.1,Zero
2,70,145,174,125,2.6,Zero
3,61,148,203,161,0.0,One
4,62,138,294,106,1.9,Three

In [39]:
scaler = StandardScaler()

In [40]:
df_encode[num_col] = scaler.fit_transform(df_encode[num_col])

In [41]:
df_encode

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target,vessels_colored_by_flourosopy,slope,sex,fasting_blood_sugar,...,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,rest_ecg_Left ventricular hypertrophy,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_Fixed Defect,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,-0.267966,-0.376556,-0.667728,0.806035,-0.037124,0,1.274980,2.0,1,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,-0.157260,0.478910,-0.841918,0.237495,1.773958,0,-0.714911,0.0,1,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1.724733,0.764066,-1.403197,-1.074521,1.342748,0,-0.714911,0.0,1,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.728383,0.935159,-0.841918,0.499898,-0.899544,0,0.280034,2.0,1,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.839089,0.364848,0.919336,-1.905464,0.739054,0,2.269926,1.0,0,0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,1.503322,-0.661712,-0.687083,-1.511859,0.394086,1,-0.714911,1.0,0,1,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
298,-1.153610,-1.346085,-2.041893,1.112172,-0.382092,1,-0.714911,1.0,0,1,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
299,-0.267966,-0.205463,0.164513,0.499898,-0.899544,0,0.280034,2.0,1,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
300,0.506972,1.619532,0.512893,-1.074521,-0.899544,0,-0.714911,2.0,1,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
301,-0.046555,-0.661712,-1.132235,-1.599327,0.307844,0,0.280034,1.0,1,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [42]:
df_encode.to_csv('../data/heart_feature_eng_2.csv', index=False)